### ISSUE TITLE
Claims I cannot install it on VS2019 Enterprise

### ISSUE THREAD

**Issue by WillEhrendreich** [nokola/InlineColorPicker#5]
?? the visx installer gives me this : 
![image](https://user-images.githubusercontent.com/55286472/143054324-cf66f760-947a-4e9a-948e-5f650656e58f.png)

install log is :

> 
> 11/23/2021 9:33:57 AM - Microsoft VSIX Installer
> 11/23/2021 9:33:57 AM - -------------------------------------------
> 11/23/2021 9:33:57 AM - vsixinstaller.exe version:
> 11/23/2021 9:33:57 AM - 17.0.5226-preview5
> 11/23/2021 9:33:57 AM - -------------------------------------------
> 11/23/2021 9:33:57 AM - Command line parameters:
> 11/23/2021 9:33:57 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Will.ehrendreich\Downloads\InlineColorPicker.vsix
> 11/23/2021 9:33:57 AM - -------------------------------------------
> 11/23/2021 9:33:57 AM - Microsoft VSIX Installer
> 11/23/2021 9:33:57 AM - -------------------------------------------
> 11/23/2021 9:33:57 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (8343192e) since it does not support extensions
> 11/23/2021 9:33:57 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (d3f915d3) since it does not support extensions
> 11/23/2021 9:33:57 AM - Initializing Install...
> 11/23/2021 9:33:57 AM - Extension Details...
> 11/23/2021 9:33:57 AM - 	Identifier         : InlineColorPicker.Microsoft.5b11f3ae-dd7e-422e-84bc-5cec46f80687
> 11/23/2021 9:33:57 AM - 	Name               : Inline Color Picker
> 11/23/2021 9:33:57 AM - 	Author             : Nokola
> 11/23/2021 9:33:57 AM - 	Version            : 2.3
> 11/23/2021 9:33:57 AM - 	Description        : Color picker extension for Visual Studio.
> 11/23/2021 9:33:57 AM - 	Locale             : en-US
> 11/23/2021 9:33:57 AM - 	MoreInfoURL        : 
> 11/23/2021 9:33:57 AM - 	InstalledByMSI     : False
> 11/23/2021 9:33:57 AM - 	SupportedFrameworkVersionRange : [4.5,)
> 11/23/2021 9:33:57 AM - 
> 11/23/2021 9:33:57 AM - 	SignatureState     : Unsigned
> 11/23/2021 9:33:57 AM - 	Supported Products : 
> 11/23/2021 9:33:57 AM - 		Microsoft.VisualStudio.Community
> 11/23/2021 9:33:57 AM - 			Version : [11.0,18.0)
> 11/23/2021 9:33:57 AM - 			ProductArchitecture : notSpecified
> 11/23/2021 9:33:57 AM - 		Microsoft.VisualStudio.Pro
> 11/23/2021 9:33:57 AM - 			Version : [11.0,18.0)
> 11/23/2021 9:33:57 AM - 			ProductArchitecture : notSpecified
> 11/23/2021 9:33:57 AM - 		Microsoft.VisualStudio.Enterprise
> 11/23/2021 9:33:57 AM - 			Version : [11.0,18.0)
> 11/23/2021 9:33:57 AM - 			ProductArchitecture : notSpecified
> 11/23/2021 9:33:57 AM - 
> 11/23/2021 9:33:57 AM - 	References         : 
> 11/23/2021 9:33:57 AM - 	Prerequisites      : 
> 11/23/2021 9:33:57 AM - 		-------------------------------------------------------
> 11/23/2021 9:33:57 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
> 11/23/2021 9:33:57 AM - 		Name         : Visual Studio core editor
> 11/23/2021 9:33:57 AM - 		Version      : [11.0,18.0)
> 11/23/2021 9:33:57 AM - 
> 11/23/2021 9:33:57 AM - Signature Details...
> 11/23/2021 9:33:57 AM - 	Extension is not signed.
> 11/23/2021 9:33:57 AM - 
> 11/23/2021 9:33:57 AM - Searching for applicable products...
> 11/23/2021 9:33:57 AM - Found installed product - Global Location
> 11/23/2021 9:33:57 AM - Found installed product - Visual Studio Enterprise 2019 (3)
> 11/23/2021 9:33:57 AM - Found installed product - Visual Studio Enterprise 2022 Current
> 11/23/2021 9:33:57 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
>    at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
>    at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
>    at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    at VSIXInstaller.App.Initialize()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by SergeyW** [comment]
Likewise. :(

**Comment by allen3371** [comment]
me to~~

**Comment by wilx01** [comment]
Yes, I have the same problem here

**Comment by ZodmanPerth** [comment]
I had this same problem as well.  I have Visual Studio 2019 Professional, yet it wasn't being recognised:
```
5/03/2022 1:22:06 PM - 	Supported Products : 
5/03/2022 1:22:06 PM - 		Microsoft.VisualStudio.Community
5/03/2022 1:22:06 PM - 			Version : [11.0,18.0)
5/03/2022 1:22:06 PM - 			ProductArchitecture : notSpecified
5/03/2022 1:22:06 PM - 		Microsoft.VisualStudio.Pro
5/03/2022 1:22:06 PM - 			Version : [11.0,18.0)
5/03/2022 1:22:06 PM - 			ProductArchitecture : notSpecified
5/03/2022 1:22:06 PM - 		Microsoft.VisualStudio.Enterprise
5/03/2022 1:22:06 PM - 			Version : [11.0,18.0)
5/03/2022 1:22:06 PM - 			ProductArchitecture : notSpecified
5/03/2022 1:22:06 PM - 
5/03/2022 1:22:06 PM - 	References         : 
5/03/2022 1:22:06 PM - 	Prerequisites      : 
5/03/2022 1:22:06 PM - 		-------------------------------------------------------
5/03/2022 1:22:06 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
5/03/2022 1:22:06 PM - 		Name         : Visual Studio core editor
5/03/2022 1:22:06 PM - 		Version      : [11.0,18.0)
5/03/2022 1:22:06 PM - 
5/03/2022 1:22:06 PM - Signature Details...
5/03/2022 1:22:06 PM - 	Extension is not signed.
5/03/2022 1:22:06 PM - 
5/03/2022 1:22:06 PM - Searching for applicable products...
5/03/2022 1:22:06 PM - Found installed product - Global Location
5/03/2022 1:22:06 PM - Found installed product - Visual Studio Professional 2019
5/03/2022 1:22:06 PM - Found installed product - Visual Studio Professional 2022
5/03/2022 1:22:06 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
```

I cloned the repo and fiddled with the vsixmanifest.  I deleted the VS Pro install target and added it back in with the default values.

![image](https://user-images.githubusercontent.com/546368/156869925-bf49ecaa-3a68-46c4-b735-667912340324.png)

After testing the installer starts in Debug mode, I created a build in Release mode.
I was then able to install it and it seems to be working.

The popup is different to what I noticed on my old machine:

![image](https://user-images.githubusercontent.com/546368/156870011-73cd44ad-2086-4036-bdf8-e2190b37b25b.png)

But it seems to work.

I suspect the author broke the install when trying to add support for VS2022.  There's no git history behind the manifest, so I think the author made some big repo changes and lost the history.

**Comment by sapsari** [comment]
> The popup is different to what I noticed on my old machine:
> 
> ![image](https://user-images.githubusercontent.com/546368/156870011-73cd44ad-2086-4036-bdf8-e2190b37b25b.png)
> 
> But it seems to work.
> 
> I suspect the author broke the install when trying to add support for VS2022. There's no git history behind the manifest, so I think the author made some big repo changes and lost the history.

It is related with commit [00719460a7f1c5f2aead994baf3804fd12d55a22](https://github.com/nokola/InlineColorPicker/commit/00719460a7f1c5f2aead994baf3804fd12d55a22), reset your repo to commit https://github.com/nokola/InlineColorPicker/commit/8865d87dddab7454ce2578d88577f78d47476cca to get the small popup, whether you are in VS2019 or VS2022
